services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=leap-sls"
      - "POSTGRES_PASSWORD=postgres"
  app:
    image: "docker_test"
    ports:
      - "8080:3001"
    

  